#! /bin/sh
#
#
# Rey's bspwm config
#

sxhkd &
~/scripts/lock.sh &
~/scripts/polybar.sh &
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V

bspc config border_width          02
bspc config window_gap            12


bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config normal_border_color   "#0f0f0f"
bspc config focused_border_color  "#c9c0c9"

bspc config pointer_modifier      mod1
bspc config click_to_focus        false
bspc config focus_follows_pointer true
bspc config pointer_action1       move

bspc rule -a Steam desktop='^3'
bspc rule -a Gimp desktop='^4'
bspc rule -a feh state=floating
